"""Immutable telemetry migration 1: adopt llm_calls and add routing metadata.

Existing extension columns, indexes, row IDs, timestamps and values are untouched.
An incompatible core is refused rather than rebuilt. No historical v16/v20 runs.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

from .runner import Migration, MigrationContext, MigrationError


_BASE_TYPES = {
    "id": "INTEGER", "ts": "TEXT", "provider": "TEXT", "model": "TEXT",
    "latency_ms": "INTEGER", "prompt_tokens": "INTEGER", "completion_tokens": "INTEGER",
    "streamed": "INTEGER", "ok": "INTEGER",
}
_EXTENSIONS = {"tier": "TEXT", "route_reason": "TEXT"}
_CREATE_SQL = """CREATE TABLE main.llm_calls (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ts TEXT DEFAULT (datetime('now')),
    provider TEXT, model TEXT, latency_ms INTEGER,
    prompt_tokens INTEGER, completion_tokens INTEGER,
    streamed INTEGER, ok INTEGER,
    tier TEXT, route_reason TEXT
)"""


def _affinity(declaration: str) -> str:
    declaration = declaration.upper()
    if "INT" in declaration:
        return "INTEGER"
    if any(part in declaration for part in ("CHAR", "CLOB", "TEXT")):
        return "TEXT"
    return "OTHER"


def _columns(context: MigrationContext) -> dict:
    obj = context.execute(
        "SELECT type FROM main.sqlite_master WHERE name='llm_calls'"
    ).fetchone()
    if obj is None:
        return {}
    if obj[0] != "table":
        raise MigrationError("llm_calls exists but is not a table")
    return {row[1]: row for row in context.execute("PRAGMA main.table_xinfo(llm_calls)")}


def _validate_schema(context: MigrationContext, *, complete: bool) -> dict:
    columns = _columns(context)
    if not columns:
        if complete:
            raise MigrationError("llm_calls is missing after migration")
        return columns
    required = {**_BASE_TYPES, **_EXTENSIONS} if complete else _BASE_TYPES
    for name, kind in required.items():
        row = columns.get(name)
        if row is None or _affinity(row[2]) != kind or row[6] != 0:
            raise MigrationError(f"llm_calls core column {name} has an incompatible shape")
    # id must remain an INTEGER rowid key so the unchanged logger can omit it.
    if (columns["id"][2].upper() != "INTEGER" or columns["id"][5] != 1
            or sum(bool(row[5]) for row in columns.values()) != 1):
        raise MigrationError("llm_calls requires its existing INTEGER primary key")
    # INTEGER PRIMARY KEY DESC and WITHOUT ROWID report the same column key,
    # but use a separate primary-key index instead of the autogenerated rowid.
    if any(row[3] == "pk" for row in context.execute("PRAGMA main.index_list(llm_calls)")):
        raise MigrationError("llm_calls primary key must generate row IDs for the logger")
    for name in _EXTENSIONS:
        if name in columns and (_affinity(columns[name][2]) != "TEXT" or columns[name][6] != 0):
            raise MigrationError(f"llm_calls routing column {name} has an incompatible shape")
    return columns


def _apply(context: MigrationContext) -> None:
    columns = _validate_schema(context, complete=False)
    if not columns:
        context.execute(_CREATE_SQL)
        return
    for name in _EXTENSIONS:
        if name not in columns:
            # Only names from the immutable definition above reach this SQL.
            context.execute(f"ALTER TABLE main.llm_calls ADD COLUMN {name} TEXT")


def _validate(context: MigrationContext) -> None:
    _validate_schema(context, complete=True)


MIGRATION = Migration(
    number=1,
    name="llm_calls",
    checksum=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
    apply=_apply,
    validate=_validate,
)
