"""«خطة الأسبوع» — one plan per child per ISO week (schema v30, Phase 1.3).

A plan is: one focus challenge, three small actions, one family worship act
and one real lesson from the curriculum for the child's age band.

**Nothing in a plan is generated by a model.** The focus titles, the actions
and the worship acts come from a hand-written bank
(`knowledge_base/curriculum/weekly_plan/`, English overlay under `i18n/en/`,
schema-checked by `ops/tools/check_curriculum_schema.py`). What is personal is
the *choice*: which challenge this week, and which three of the four actions.
That is decided from what the app already knows about the child — the
parent's chosen challenge, the remembered facts, how earlier follow-ups went —
and falls back to the demand map (prayer → anger → sleep → study → screens →
fear → siblings) when it knows nothing. An action whose wording matches a
strategy the parent reported as not working is skipped for the spare one.

Coverage: every band has a bank. prenatal-1 and 0-3 share `baby` (bonding,
sleep, screens, a calm home of faith — no study or anger topics at that age);
2-3 and 4-6 share `early`; 7-9 and 10-12 `school`; 13-15 and 16-18 `teen`.

A plan is built lazily on first read in a week and cached per (child, week,
language), so it does not change under the parent mid-week.
"""
from __future__ import annotations

import json
import logging
import sqlite3
from datetime import date, datetime, timedelta, timezone
from functools import lru_cache
from pathlib import Path
from typing import Optional

from app import curriculum_loader as cl
from app.core.taxonomy import age_equivalents, canonical_age_group
from app.db.init_db import get_conn
from app.services import content_lang
from app.services.child_memory import _similar, _tokens, memory_enabled

logger = logging.getLogger(__name__)

BANK_DIR = Path(__file__).resolve().parents[3] / "knowledge_base" / "curriculum" / "weekly_plan"

BAND_GROUP = {
    "prenatal-1": "baby", "0-3": "baby",
    "2-3": "early", "4-6": "early",
    "7-9": "school", "10-12": "school",
    "13-15": "teen", "16-18": "teen",
}

# The demand map, measured on 1,284 real questions (2026-08-13): the order a
# plan falls back to when the app knows nothing about the child yet.
DEMAND_ORDER = ("prayer", "anger", "sleep", "study", "screens", "fear", "siblings", "bonding")

# «رحلة الطفل» challenge keys (coach_service.CHALLENGE_TOPICS) → plan topics.
CHALLENGE_TO_TOPIC = {
    "sleep": "sleep", "screens": "screens", "tantrums": "anger",
    "hitting": "anger", "fear": "fear", "study": "study",
}

_TOPIC_KEYWORDS = {
    "prayer": ("صلا", "صلّ", "يصلي", "تصلي", "وضوء", "قرآن", "القران", "مسجد", "عباد",
               "pray", "salah", "salat", "quran", "qur'an", "mosque", "worship"),
    "anger": ("غضب", "عصب", "عناد", "عنيد", "يعاند", "صراخ", "يصرخ", "ضرب", "نوب", "تمرد",
              "anger", "angry", "tantrum", "stubborn", "yell", "scream", "hits", "hitting", "defian"),
    "sleep": ("نوم", "ينام", "تنام", "سهر", "يستيقظ", "sleep", "bedtime", "wakes", "night"),
    "study": ("مذاكر", "دراس", "مدرس", "واجب", "امتحان", "تركيز", "study", "homework", "school",
              "exam", "focus", "grades"),
    "screens": ("شاش", "تابلت", "هاتف", "موبايل", "جوال", "يوتيوب", "تيك توك", "ألعاب إلكترونية",
                "screen", "tablet", "phone", "ipad", "youtube", "tiktok", "gaming", "video game"),
    "fear": ("خوف", "يخاف", "تخاف", "قلق", "فزع", "كوابيس", "رهاب",
             "fear", "afraid", "scared", "anxi", "nightmare", "worr"),
    "siblings": ("غيرة", "الغيرة", "يغار", "تغار", "أخوه", "أخته", "إخوت", "اخوت", "الإخوة",
                 "sibling", "jealous", "brother", "sister"),
}

_REASON_TEXT = {
    "ar": {
        "parent_challenge": "لأنك اخترت هذا التحدي في «رحلة الطفل».",
        "memory": "بناءً على ما أخبرتنا به عن طفلك.",
        "age_default": "من أكثر ما يسأل عنه الآباء في هذا العمر.",
    },
    "en": {
        "parent_challenge": "Because you chose this as your child's current challenge.",
        "memory": "Based on what you have told us about your child.",
        "age_default": "One of the most common needs at this age.",
    },
}


def iso_week(d: date) -> tuple[str, date]:
    """('2026-W40', Monday of that week)."""
    year, week, weekday = d.isocalendar()
    return f"{year}-W{week:02d}", d - timedelta(days=weekday - 1)


def topic_of(text: str) -> Optional[str]:
    t = (text or "").lower()
    for topic, words in _TOPIC_KEYWORDS.items():
        if any(w in t for w in words):
            return topic
    return None


# ── Bank ──────────────────────────────────────────────────────────────────


@lru_cache(maxsize=16)
def _load(group: str, lang: Optional[str]) -> dict:
    path = content_lang.localised(BANK_DIR, f"weekly_plan_{group}.json", lang)
    return json.loads(path.read_text(encoding="utf-8"))


def load_bank(group: str, lang: Optional[str]) -> dict:
    """The Arabic bank (keys, lessons, order) with the overlay's text on top.

    Structure always comes from the Arabic file; the English file supplies
    text by key. A key the overlay lacks keeps its Arabic text rather than
    vanishing — content_lang's rule: a missing translation is not a missing
    feature.
    """
    base = _load(group, None)
    code = content_lang.normalise(lang)
    if not code:
        return base
    overlay = _load(group, code)
    if overlay is base:
        return base
    topics_en = {t["key"]: t for t in overlay.get("topics", [])}
    worship_en = {w["key"]: w["text"] for w in overlay.get("worship", [])}
    merged = {**base, "topics": [], "worship": []}
    for t in base["topics"]:
        o = topics_en.get(t["key"], {})
        actions_en = {a["key"]: a["text"] for a in o.get("actions", [])}
        merged["topics"].append({
            **t,
            "focus": o.get("focus", t["focus"]),
            "actions": [
                {**a, "text": actions_en.get(a["key"], a["text"])} for a in t["actions"]
            ],
        })
    merged["worship"] = [
        {**w, "text": worship_en.get(w["key"], w["text"])} for w in base["worship"]
    ]
    return merged


# ── Signals ───────────────────────────────────────────────────────────────


def _signals(conn: sqlite3.Connection, device_id: str, child_id: int,
             use_memory: bool) -> dict:
    """What the app knows that should shape this week's plan."""
    out: dict = {"challenge": None, "memory_topics": [], "failed": []}
    try:
        row = conn.execute(
            "SELECT challenge_key FROM child_challenges WHERE device_id = ? "
            "AND child_id = ? AND status = 'active' ORDER BY id DESC LIMIT 1",
            (device_id, child_id),
        ).fetchone()
        if row is not None:
            out["challenge"] = CHALLENGE_TO_TOPIC.get(row["challenge_key"])
    except sqlite3.Error:
        pass
    if not use_memory:
        return out
    facts = conn.execute(
        "SELECT category, fact FROM child_facts WHERE device_id = ? AND child_id = ? "
        "AND status = 'active' ORDER BY updated_at DESC LIMIT 30",
        (device_id, child_id),
    ).fetchall()
    for f in facts:
        if f["category"] in ("challenge", "goal", "outcome", "tried_strategy"):
            t = topic_of(f["fact"])
            if t:
                out["memory_topics"].append(t)
    # A strategy the parent reported as not working must not come back as
    # one of this week's three actions.
    for r in conn.execute(
        "SELECT strategy, topic FROM followups WHERE device_id = ? AND child_id = ? "
        "AND status = 'answered' AND outcome IN ('didnt_work', 'partly') "
        "ORDER BY answered_at DESC LIMIT 10",
        (device_id, child_id),
    ).fetchall():
        out["failed"].append(r["strategy"])
        if r["topic"] in DEMAND_ORDER:
            out["memory_topics"].append(r["topic"])
    return out


def _choose_focus(topics: list[dict], signals: dict, week_no: int) -> tuple[dict, str]:
    by_key = {t["key"]: t for t in topics}
    if signals["challenge"] in by_key:
        return by_key[signals["challenge"]], "parent_challenge"
    if signals["memory_topics"]:
        # Most mentioned wins; ties go to the most recent mention.
        counts: dict[str, int] = {}
        for t in signals["memory_topics"]:
            if t in by_key:
                counts[t] = counts.get(t, 0) + 1
        if counts:
            best = max(counts, key=lambda k: (counts[k], -signals["memory_topics"].index(k)))
            return by_key[best], "memory"
    ordered = [by_key[k] for k in DEMAND_ORDER if k in by_key]
    return ordered[week_no % len(ordered)], "age_default"


def _overlaps_failed(action_text: str, failed: list[str]) -> bool:
    for s in failed:
        if _similar(action_text, s) or len(_tokens(action_text) & _tokens(s)) >= 3:
            return True
    return False


def _choose_actions(topic: dict, failed: list[str]) -> tuple[list[dict], bool]:
    keep = [a for a in topic["actions"] if not _overlaps_failed(a["text"], failed)]
    adapted = len(keep) < len(topic["actions"])
    if len(keep) < 3:  # never fewer than three: refill from the skipped ones
        keep += [a for a in topic["actions"] if a not in keep][: 3 - len(keep)]
    return keep[:3], adapted


def _completed_lessons(conn: sqlite3.Connection, device_id: str, child_id: int) -> set[str]:
    try:
        rows = conn.execute(
            "SELECT lesson_id FROM lesson_progress WHERE device_id = ? "
            "AND child_id IN (?, 0) AND status = 'completed'",
            (device_id, child_id),
        ).fetchall()
    except sqlite3.Error:
        return set()
    return {r["lesson_id"] for r in rows}


def _choose_lesson(topic: dict, band: str, completed: set[str],
                   lang: Optional[str]) -> Optional[dict]:
    lessons_by_band = topic.get("lessons") or {}
    candidates: list[str] = []
    for b in [band] + [x for x in age_equivalents(band) if x != band]:
        for lid in lessons_by_band.get(b, []):
            if lid not in candidates:
                candidates.append(lid)
    published = [lid for lid in candidates if cl.get_lesson(lid) is not None]
    if not published:
        return None
    pick = next((lid for lid in published if lid not in completed), published[0])
    lesson = cl.get_lesson(pick, lang=lang) or {}
    return {
        "id": pick,
        "title": lesson.get("title", ""),
        "path_id": lesson.get("path_id"),
        "estimated_minutes": lesson.get("estimated_minutes"),
        "completed": pick in completed,
    }


# ── Public ────────────────────────────────────────────────────────────────


def build_plan(device_id: str, child_id: int, *, today: date,
               lang: Optional[str]) -> dict:
    """Assemble (not cache) the plan for the ISO week containing `today`."""
    code = content_lang.normalise(lang) or "ar"
    week, monday = iso_week(today)
    week_no = int(week.split("-W")[1])
    conn = get_conn()
    try:
        child = conn.execute(
            "SELECT age_group FROM child_profiles WHERE id = ? AND device_id = ?",
            (child_id, device_id),
        ).fetchone()
        if child is None:
            raise LookupError("child")
        band = canonical_age_group(child["age_group"] or "")
        group = BAND_GROUP.get(band) or BAND_GROUP.get(child["age_group"] or "", "early")
        bank = load_bank(group, code)
        signals = _signals(conn, device_id, child_id, memory_enabled(device_id))
        completed = _completed_lessons(conn, device_id, child_id)
    finally:
        conn.close()

    topic, reason = _choose_focus(bank["topics"], signals, week_no)
    actions, adapted = _choose_actions(topic, signals["failed"])
    worship = bank["worship"][(week_no + child_id) % len(bank["worship"])]
    return {
        "child_id": child_id,
        "week": week,
        "week_start": monday.isoformat(),
        "lang": code,
        "band": band,
        "focus": {
            "topic": topic["key"],
            "title": topic["focus"],
            "reason": reason,
            "reason_text": _REASON_TEXT[code if code in _REASON_TEXT else "ar"][reason],
        },
        "actions": [{"key": a["key"], "text": a["text"]} for a in actions],
        "adapted_from_outcomes": adapted,
        "worship": {"key": worship["key"], "text": worship["text"]},
        "lesson": _choose_lesson(topic, band, completed, code if code != "ar" else None),
        "source": "bank",
    }


def _stored_offset(device_id: str) -> Optional[int]:
    """The UTC offset the app last reported for this device (child_memory)."""
    conn = get_conn()
    try:
        row = conn.execute("SELECT tz_offset_minutes FROM child_memory_settings "
                           "WHERE device_id = ?", (device_id,)).fetchone()
    except sqlite3.Error:
        return None
    finally:
        conn.close()
    return None if row is None or row["tz_offset_minutes"] is None else int(row["tz_offset_minutes"])


def get_weekly_plan(device_id: str, child_id: int, *, lang: Optional[str] = None,
                    tz_offset_minutes: Optional[int] = None,
                    now: Optional[datetime] = None) -> dict:
    """This week's plan, built once and then served from `weekly_plans`.

    The week is the parent's local ISO week (Monday start), from the UTC offset
    the client sent — or, when it sent none, the one it last reported, and UTC
    only when there is neither (PR #26 review F7: a missing offset is not 0).
    """
    code = content_lang.normalise(lang) or "ar"
    now = now or datetime.now(timezone.utc)
    if tz_offset_minutes is None:
        tz_offset_minutes = _stored_offset(device_id)
    offset = max(-14 * 60, min(14 * 60, int(tz_offset_minutes or 0)))
    local_day = (now + timedelta(minutes=offset)).date()
    week, _ = iso_week(local_day)
    conn = get_conn()
    try:
        row = conn.execute(
            "SELECT plan_json, created_at FROM weekly_plans WHERE device_id = ? "
            "AND child_id = ? AND iso_week = ? AND lang = ?",
            (device_id, child_id, week, code),
        ).fetchone()
    finally:
        conn.close()
    if row is not None:
        try:
            plan = json.loads(row["plan_json"])
            plan["generated_at"] = row["created_at"]
            return plan
        except (json.JSONDecodeError, TypeError):
            logger.warning("weekly plan: unreadable cached row — rebuilding")

    plan = build_plan(device_id, child_id, today=local_day, lang=code)
    conn = get_conn()
    try:
        conn.execute(
            "INSERT INTO weekly_plans (device_id, child_id, iso_week, lang, plan_json) "
            "VALUES (?, ?, ?, ?, ?) "
            "ON CONFLICT(device_id, child_id, iso_week, lang) DO NOTHING",
            (device_id, child_id, week, code, json.dumps(plan, ensure_ascii=False)),
        )
        conn.commit()
        row = conn.execute(
            "SELECT plan_json, created_at FROM weekly_plans WHERE device_id = ? "
            "AND child_id = ? AND iso_week = ? AND lang = ?",
            (device_id, child_id, week, code),
        ).fetchone()
    finally:
        conn.close()
    # Two first readers racing: the row that won is the plan, for both.
    stored = json.loads(row["plan_json"]) if row else plan
    stored["generated_at"] = row["created_at"] if row else None
    return stored
