#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# Deploy Tutor Guardian fine-tuned GGUF to Ollama (home server or VPS)
# ──────────────────────────────────────────────────────────────────────────────
# Usage:
#   ./deploy_model.sh                    — deploy to localhost Ollama
#   ./deploy_model.sh --remote root@IP   — SCP to remote + deploy
#   ./deploy_model.sh --model tg-tutor   — specify model name
#   ./deploy_model.sh --gguf path        — specify GGUF path
#
# Prerequisites:
#   - Ollama installed and running on target
#   - GGUF file generated by Colab notebook
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

MODEL_NAME="${MODEL_NAME:-tg-tutor}"
GGUF_SRC="${GGUF_SRC:-$PROJECT_ROOT/ops/ollama/tg-tutor.gguf}"
MODELFILE="$PROJECT_ROOT/ops/ollama/Modelfile.tg-tutor"
REMOTE_TARGET=""          # e.g. root@192.168.1.100
OLLAMA_HOST=""            # e.g. http://192.168.1.100:11434
LOCAL=false

# ── Help ─────────────────────────────────────────────────────────────────────
usage() {
    echo "Usage: $0 [--remote user@host] [--model name] [--gguf path] [--local]"
    echo ""
    echo "  --remote   SCP target (e.g. root@192.168.1.100)"
    echo "  --model    Model name in Ollama (default: tg-tutor)"
    echo "  --gguf     Path to GGUF file (default: ops/ollama/tg-tutor.gguf)"
    echo "  --local    Deploy to local Ollama (default if no --remote)"
    exit 1
}

# ── Parse args ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote) REMOTE_TARGET="$2"; shift 2 ;;
        --model) MODEL_NAME="$2"; shift 2 ;;
        --gguf) GGUF_SRC="$2"; shift 2 ;;
        --local) LOCAL=true; shift ;;
        --help|-h) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

if [[ -z "$REMOTE_TARGET" ]]; then
    LOCAL=true
fi

# ── Check prerequisites ──────────────────────────────────────────────────────
if [[ ! -f "$GGUF_SRC" ]]; then
    echo "❌ GGUF not found: $GGUF_SRC"
    echo "   Generate it first with: ops/colab/finetune_tg.ipynb"
    exit 1
fi

if [[ ! -f "$MODELFILE" ]]; then
    echo "❌ Modelfile not found: $MODELFILE"
    exit 1
fi

GGUF_SIZE=$(du -h "$GGUF_SRC" | cut -f1)
echo "📦 GGUF: $GGUF_SRC ($GGUF_SIZE)"
echo "📄 Modelfile: $MODELFILE"
echo "🏷️  Model name: $MODEL_NAME"

# ── Deploy locally ───────────────────────────────────────────────────────────
deploy_local() {
    echo ""
    echo "🚀 Deploying to LOCAL Ollama..."
    echo ""

    MODELL_DIR="$(dirname "$MODELFILE")"
    GGUF_DEST="$MODELL_DIR/tg-tutor.gguf"

    # Symlink or copy GGUF next to Modelfile
    if [[ "$GGUF_SRC" != "$GGUF_DEST" ]]; then
        echo "📋 Copying GGUF to $GGUF_DEST ..."
        cp "$GGUF_SRC" "$GGUF_DEST"
    fi

    echo "🔨 Creating Ollama model: $MODEL_NAME ..."
    cd "$MODELL_DIR"
    ollama create "$MODEL_NAME" -f "$MODELFILE"
    echo "✅ Model created!"

    echo "🧪 Testing..."
    echo ""
    ollama run "$MODEL_NAME" "كيف أتعامل مع ابني الذي يغضب كثيراً؟" 2>/dev/null || true

    echo ""
    echo "✅ Done! Model '$MODEL_NAME' ready on local Ollama"
}

# ── Deploy remote ────────────────────────────────────────────────────────────
deploy_remote() {
    echo ""
    echo "🚀 Deploying to REMOTE: $REMOTE_TARGET"
    echo ""

    REMOTE_DIR="/root/ollama-models/$MODEL_NAME"

    # Create remote dir and copy files
    echo "📂 Creating remote directory..."
    ssh "$REMOTE_TARGET" "mkdir -p $REMOTE_DIR"

    echo "📋 Copying GGUF ($GGUF_SIZE)..."
    scp "$GGUF_SRC" "$REMOTE_TARGET:$REMOTE_DIR/tg-tutor.gguf"

    echo "📋 Copying Modelfile..."
    scp "$MODELFILE" "$REMOTE_TARGET:$REMOTE_DIR/Modelfile"

    echo "🔨 Creating Ollama model on remote..."
    ssh "$REMOTE_TARGET" "cd $REMOTE_DIR && ollama create $MODEL_NAME -f Modelfile"

    echo "🧪 Testing..."
    ssh "$REMOTE_TARGET" "ollama run $MODEL_NAME 'كيف أتعامل مع ابني الذي يغضب كثيراً؟'" 2>/dev/null || true

    echo ""
    echo "✅ Done! Model '$MODEL_NAME' deployed to $REMOTE_TARGET"
}

# ── Main ─────────────────────────────────────────────────────────────────────
if [[ "$LOCAL" == true ]]; then
    deploy_local
else
    deploy_remote
fi
